services:
    db:
        image: mysql:8.0-oracle
        container_name: database
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data: