services:
  # --- Base de Datos ---
  db:
    image: mysql:8.0-oracle
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    container_name: openpunch-database
    restart: always
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=openpunch # Obligatorio para que funcionen los scripts de init
    networks:
      - backend-private
    volumes:
      # PERSISTENCIA: Bind-mount local (Ignorado en git)
      - ./docker/mysql/data:/var/lib/mysql
      # INICIALIZACIÓN: Scripts SQL (Dentro de git)
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  # --- Spring Boot ---
  app:
    build: .
    container_name: openpunch-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - TZ=Europe/Madrid
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/openpunch?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Madrid
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - frontend-public
      - backend-private

networks:
  frontend-public:
    driver: bridge
  backend-private:
    internal: true
    
