services:
    # --- Base de Datos ---
    db:
        image: mysql:8.0-oracle
        container_name: openpunch-database
        restart: always
        environment:
            - TZ=Europe/Madrid
            - MYSQL_ROOT_PASSWORD=1234
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    # --- Spring Boot ---
    app:
        build: .
        container_name: openpunch-app
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - TZ=Europe/Madrid
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/openpunch?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Madrid
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=1234

volumes:
    mysql_data: